export const content = {
  ar: {
    nav: {
      links: [
        { label: 'الرئيسية', href: '#home' },
        { label: 'عن الشركة', href: '#about' },
        { label: 'منتجاتنا', href: '#products' },
        { label: 'المركز الإعلامي', href: '#media' },
        { label: 'دليل المتعاملين', href: '#guide' },
        { label: 'تواصل معنا', href: '#contact' },
      ],
      hotline: '19996',
    },
    hero: {
      slides: [
        {
          image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1600',
          headline: 'التعمير للتمويل العقاري',
          subline: 'بلا حدود',
          cta: 'عن الشركة',
        },
        {
          image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600',
          headline: 'نمول المستقبل، نبني الطموحات',
          subline: '',
          cta: 'المنتجات',
        },
        {
          image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1600',
          headline: 'نخطط لخطوتك القادمة',
          subline: '',
          cta: 'اعرف المزيد',
        },
      ],
    },
    about: {
      bannerSubtitle: 'رواد التمويل العقاري في مصر لأكثر من عشرين عاماً',
      headline: 'شركة التعمير للتمويل العقاري (الأولى)',
      body: 'التعمير هي رائدة مجال التمويل العقاري بمصر كونها الشركة الأولى في القطاع من حيث التأسيس. أنشئت الشركة في أغسطس من العام 2003 بمساهمة وتحالف العديد من الجهات البنكية والحكومية الرائدة. بدأت الشركة عمليات التمويل الفعلية في فبراير 2004 ويبلغ الآن رأس المال المدفوع لها 1.504 مليار جنيه مصري.',
      intro: 'التعمير للتمويل العقاري هي شركة التمويل العقاري الوطنية الأولى والأعرق والتي تخدم كل شرائح العملاء بتخصص وكفاءة، نحن الحليف الأساسي مع القطاعات المتعلقة بمجال التمويل العقاري ولنا دور مجتمعي هام في المساهمة في تطبيق معايير التنمية المستدامة داخل جمهورية مصر العربية.',
      mission: {
        title: 'مهمتنا',
        body: 'مهمتنا هي تقديم حلول تمويلية متميزة ومتطورة لعملائنا عبر تمكينهم من تحقيق أهدافهم السكنية والإستثمارية ووضع رضائهم في المقام الأول لتعزيز دور الشركة الفعال في تعمير ونهضة المجتمع المصري مع ضمان أعلى عائد على الإستثمار لمساهمي الشركة مع الإلتزام بتطبيق معايير التنمية المستدامة.',
      },
      vision: {
        title: 'رؤيتنا',
        body: 'الحفاظ على ريادتنا للمجال وتطويره في ضوء معايير التنمية المستدامة.',
      },
      values: {
        title: 'قيمنا',
        items: [
          { title: 'التطور والريادة', desc: 'نبتكر حلول خلاقة ونتطلع لما هو أبعد من أهدافنا الحالية لحرصنا على إرضاء عملائنا والحفاظ على ريادتنا.' },
          { title: 'روح الفريق', desc: 'نعمل دائماً كفريق يتكاتف ويخلص ويتعاون لتعزيز كفاءة الشركة وصدارتها.' },
          { title: 'التفوق', desc: 'جدارتنا بالريادة نابعة من أداء فريق عمل الشركة لمهامهم بدقة وتناغم ونزاهة.' },
          { title: 'الإلتزام والحوكمة', desc: 'نرسخ دائماً أسس الممارسات المهنية الأفضل وأخلاقيات العمل ونلتزم بقواعد المنافسة الشريفة والحوكمة في جميع تعاملاتنا.' },
          { title: 'الإستدامة', desc: 'نعمل في ضوء مبادئ الإستدامة عبر الإستخدام الأمثل للموارد مع تشجيع وتنمية التمويل الأخضر.' },
        ],
      },
      shareholders: {
        title: 'هيكل المساهمين',
        items: [
          'هيئة المجتمعات العمرانية',
          'بنك التعمير والإسكان',
          'شركة مصر لتأمينات الحياة',
          'شركة مصر للتأمين',
          'هيئة الأوقاف المصرية',
          'بنك الإستثمار القومي',
          'الشركة القابضة للتشييد والتعمير',
          'بنك مصر إيران للتنمية',
          'الشركة العربية للمشروعات والتطوير العمراني',
          'شركة الإسكندرية والسعودية للمشروعات السياحية',
          'شركة نوفا بارك القاهرة',
          'شركة سان ستيفانو للإستثمار العقاري',
          'شركة الإسكندرية للإستثمار العقاري',
        ],
      },
      board: {
        title: 'أعضاء مجلس الإدارة',
        items: [
          { name: 'تامر نجم', role: 'رئيس مجلس الإدارة' },
          { name: 'أيمن عبدالحميد', role: 'العضو المنتدب والرئيس التنفيذي' },
          { name: 'حسن الفار', role: 'عضو مجلس الإدارة' },
          { name: 'أشرف نجم', role: 'عضو مجلس الإدارة' },
          { name: 'غادة البديوي', role: 'عضو مجلس الإدارة' },
          { name: 'مدحت عبدالغني', role: 'عضو مجلس الإدارة' },
          { name: 'وليد عباس', role: 'عضو مجلس الإدارة' },
          { name: 'مصطفى عبدالمنعم الحيوان', role: 'عضو مجلس الإدارة' },
          { name: 'أحمد القمحاوي', role: 'عضو مجلس الإدارة' },
        ],
      },
      management: {
        title: 'فريق الإدارة',
        items: [
          {
            name: 'أيمن عبدالحميد',
            role: 'العضو المنتدب والرئيس التنفيذي',
            bio: 'يمتلك خبرة أكثر من 20 عام من أصل 32 عام في مجال التمويل العقاري والقطاع المصرفي. حصل على درجة البكالوريوس في علوم الإدارة من أكاديمية السادات. يشغل حالياً منصب العضو المنتدب والرئيس التنفيذي لشركة التعمير للتمويل العقاري (الأولى)، وذلك بعد توليه منصب الرئيس التنفيذي لشركة أملاك - مصر للتمويل العقاري، كما ترأس القسم التجاري في البنك التجاري الدولي (CIB).',
          },
          {
            name: 'أحمد قطب',
            role: 'مدير عام – إدارة المالية والخزانة',
            bio: 'التحق بشركة التعمير للتمويل العقاري عام 2021 ويمتلك عشرين عاماً من الخبرة في مجالات المراجعة الداخلية والخارجية. حاصل على درجة البكالوريوس في المحاسبة والماليات.',
          },
          {
            name: 'أحمد أسامة',
            role: 'مدير عام – إدارة الشئون القانونية',
            bio: 'التحق بشركة التعمير منذ 2021 ويمتلك أكثر من تسعة عشر عاماً من الخبرة في المجال القانوني. تخرج من كلية الحقوق جامعة عين شمس وحاصل على شهادة الماجستير في قانون التجارة الدولي.',
          },
          {
            name: 'أحمد نبيل',
            role: 'مدير عام – قطاع المخاطر',
            bio: 'التحق بشركة التعمير في عام 2021 ويمتلك الخبرة والتخصص في القطاع المالي سواء المصرفي أو غير المصرفي بعمله لمدة تقارب العشرين عام.',
          },
          {
            name: 'أسماء بكر',
            role: 'مدير عام – إدارة المراقبة والمراجعة الداخلية',
            bio: 'تمتلك خبرة مهنية متزايدة لأكثر من 20 عاماً في تقديم خدمات المراجعة والإستشارات المهنية للشركات متعددة الجنسيات. مراجع داخلي معتمد (CIA) من معهد المراجعين الداخليين (IIA) - الولايات المتحدة الأمريكية.',
          },
          {
            name: 'محمد سلامة',
            role: 'مدير عام – إدارة الاستراتيجية والعلاقات الخارجية',
            bio: 'يمتلك أكثر من 17 عام من الخبرة في مجال التسويق لقطاعي العقارات والمؤسسات المالية. حاصل على بكالوريوس إدارة أعمال وماجستير في التسويق.',
          },
          {
            name: 'صبري بكر',
            role: 'مساعد مدير عام – إدارة تكنولوجيا المعلومات (البرامج والتطبيقات)',
            bio: 'يمتلك أكثر من 20 سنة من الخبرة في مجالات الحسابات والبرامج والتطبيقات. انضم لشركة التعمير في عام 2013.',
          },
          {
            name: 'نيفين أمين',
            role: 'مدير رئيسي – الفروع',
            bio: 'حاصلة على بكالوريوس تجارة ولديها 10 سنوات من الخبرة في مجال إدارة العمليات والتشغيل واللوجيستيات.',
          },
          {
            name: 'شيماء إبراهيم',
            role: 'مساعد مدير عام – إدارة الإئتمان',
            bio: 'تمتلك أكثر من 17 عام من الخبرة في مجال المؤسسات المالية. بدأت حياتها العملية موظفة بإدارة الإئتمان بشركة التعمير.',
          },
          {
            name: 'محمد مصطفى',
            role: 'مساعد مدير عام – إدارة الموارد البشرية',
            bio: 'حاصل على بكالوريوس تجارة وشهادة HRM CP المتخصصة في إدارة الموارد البشرية من الغرفة التجارية الأمريكية بالقاهرة. يمتلك أكثر من 20 عام من الخبرة.',
          },
          {
            name: 'مصطفى عبدالهادي',
            role: 'مدير عام – قطاع العمليات',
            bio: 'التحق بشركة التعمير في عام 2023، ويمتلك أكثر من ثمانية عشر عاماً من الخبرة في مجالات البنوك والتمويل العقاري. حاصل على شهادة CMA.',
          },
          {
            name: 'محمد حسين',
            role: 'نائب مدير عام – إدارة الشئون الإدارية والمشتريات',
            bio: 'حاصل على بكالوريوس تجارة وأكثر من 25 عام من الخبرة في مجال العقارات. قضى معظم سنوات خبرته في دولة الإمارات العربية المتحدة.',
          },
          {
            name: 'محمد وجدي',
            role: 'مساعد مدير عام – إدارة المبيعات وتطوير الأعمال',
            bio: 'يمتلك خبرة أكثر من 9 سنوات في مجال المبيعات والتمويل. حاصل على ليسانس حقوق من جامعة القاهرة.',
          },
        ],
      },
    },
    products: {
      title: 'منتجاتنا وخدماتنا',
      bannerSubtitle: 'ملتزمون بتقديم أفضل الحلول التمويلية',
      cards: [
        {
          title: 'تَمَلُّك',
          desc: 'التعمير تقدم لك أو لشركتك فرصة مميزة لتمويل تملك أي وحدة سكنية؛ إدارية؛ تجارية؛ خدمية أو طبية بقيمة – هي الأضخم في المجال – بأنظمة سداد مرنة تمتد لسنوات.',
          accent: '#E40521',
          icon: 'Building2',
          documentsClient: [
            'صورة بطاقة الرقم القومي (للأفراد)',
            'شهادة مفردات الراتب (للأفراد)',
            'كشف حساب شخصي لمدة لا تقل عن 6 أشهر للأفراد أو كشف حساب لمدة لا تقل عن سنة للشركات',
            'بطاقة ضريبية (للشركات)',
            'سجل تجاري (للشركات)',
            'صورة من عقد تأسيس الشركة (للشركات)',
            'آخر 3 ميزانيات للنشاط (للشركات)',
          ],
          documentsUnit: [
            'عقد مسجل للوحدة محل التمويل (للوحدات المسجلة)',
            'محضر الاستلام (للوحدات التابعة للمدن الجديدة)',
            'شهادة تصرفات عقارية',
            'ترخيص المباني (إلا للوحدات المسجلة)',
            'موقف مالي وعقاري للوحدة (إلا للوحدات المسجلة)',
            'إخطار أو قرار التخصيص أو عقد بيع الأرض المقام عليها المشروع (إلا للوحدات المسجلة)',
            'القرار الوزاري بإعتماد التخطيط والتقسيم لأرض المشروع',
          ],
        },
        {
          title: 'وفرة',
          desc: 'التعمير تقدم لك أو لشركتك فرصة مميزة لتوفير سيولة مالية – هي الأضخم في المجال - على أي وحدة سكنية؛ إدارية؛ تجارية؛ خدمية أو طبية بأنظمة سداد مرنة تمتد لسنوات.',
          accent: '#414042',
          icon: 'TrendingUp',
          documentsClient: [
            'صورة بطاقة الرقم القومي (للأفراد)',
            'شهادة مفردات الراتب (للأفراد)',
            'كشف حساب شخصي لمدة لا تقل عن 6 أشهر للأفراد أو كشف حساب لمدة لا تقل عن سنة للشركات',
            'بطاقة ضريبية (للشركات)',
            'سجل تجاري (للشركات)',
            'صورة من عقد تأسيس الشركة (للشركات)',
            'آخر 3 ميزانيات للنشاط (للشركات)',
          ],
          documentsUnit: [
            'عقد مسجل للوحدة محل التمويل (للوحدات المسجلة)',
            'محضر الاستلام (للوحدات التابعة للمدن الجديدة)',
            'شهادة تصرفات عقارية',
            'ترخيص المباني (إلا للوحدات المسجلة)',
            'موقف مالي وعقاري للوحدة (إلا للوحدات المسجلة)',
            'إخطار أو قرار التخصيص أو عقد بيع الأرض المقام عليها المشروع (إلا للوحدات المسجلة)',
            'القرار الوزاري بإعتماد التخطيط والتقسيم لأرض المشروع',
          ],
        },
        {
          title: 'محافظ',
          desc: 'يتيح منتج محافظ من التعمير لشركات التطوير العقاري إحالة حقوق المحفظة العقارية الخاصة بها المالية والعقارية مقابل سيولة مالية - هي الأضخم في قطاع التمويل - لتمكنها من اغتنام فرص إستثمارية جديدة وتحقيق نمو متسارع.',
          accent: '#6D6E71',
          icon: 'Briefcase',
          documentsClient: [
            'أصل مستخرج حديث من سجل تجاري ساري (لم يمر على صدوره أكثر من ثلاثة أشهر)',
            'صورة من البطاقة الضريبية + ما يفيد تقديم آخر إقرار ضريبي أو شهادة من المحاسب القانوني بالموقف من الضرائب والتأمينات',
            'صورة من عقد تأسيس الشركة / صحيفة الشركات (للشركات المساهمة) بالإضافة إلى كافة التعديلات',
            'صورة عقد إيجار أو تمليك مقر النشاط الرئيسي والفرعي',
            'كشف حساب بنكي بإسم الشركة معتمد من بنك التعامل لمدة لا تقل عن عام',
            'صورة آخر 3 ميزانيات مالية معتمدة من المراقب المالي وموقعة ممن له حق التوقيع بالشركة',
            'صورة من كارنيه المحاسب القانوني الخاص بالشركة (على أن يكون ساري)',
            'نبذة عن الشركة ومجلس الإدارة',
          ],
          documentsUnit: [],
        },
      ],
      services: {
        title: 'خدماتنا',
        items: [
          { title: 'التقييم العقاري', desc: 'تمكنك خدمة التقييم العقاري عند دراسة ملف التمويل من معرفة القيمة العادلة لعملية شراء الوحدات العقارية لضمان أفضل إستثمار.', icon: 'Search' },
          { title: 'تقرير I-score', desc: 'تدرس "الأولى" تقرير I-score الخاص بالعملاء المتقدمين للحصول على تمويل عقاري ليكون العميل على علم تام بتقييمه الإئتماني.', icon: 'FileText' },
          { title: 'التأمين على الحياة', desc: 'التمويل من "الأولى" يؤمن تسوية المديونية بالكامل عن العملاء في حالات الوفاة لا قدر الله.', icon: 'Shield' },
          { title: 'التأمين ضد الحريق', desc: 'التمويل من "الأولى" يؤمن تغطية حالات الحريق للوحدات محل التمويل.', icon: 'Flame' },
        ],
      },
      form: {
        title: 'استفسار',
        fields: {
          name: 'الإسم',
          phone: 'رقم التليفون',
          occupation: 'الوظيفة',
          occupationOptions: ['موظف', 'أعمال حرة', 'مهن حرة', 'أخرى'],
          unitType: 'نوع الوحدة',
          unitTypeOptions: ['سكني', 'تجاري', 'إداري', 'خدمي أو طبي', 'أخرى'],
          product: 'المنتج',
          productOptions: ['تَمَلُّك', 'وفرة', 'محافظ'],
          income: 'الدخل الشهري',
          finance: 'التمويل المطلوب',
          inquiry: 'الإستفسار',
          submit: 'أرسل',
        },
      },
      cta: 'اعرف المزيد',
    },
    cbe: {
      headline: 'مبادرة البنك المركزي المصري',
      subline: 'كان لشركة التعمير للتمويل العقاري الريادة في المساهمة والمشاركة في مبادرة البنك المركزي المصري لدعم التمويل العقاري لمحدودي ومتوسطي الدخل منذ تدشينها لتأصيل دورها الجوهري في تنمية المجتمع تواكباً مع رؤية الدولة واستراتيجيتها وذلك بتمويل أكثر من 7,000 عميل بإجمالي أكثر من مليار جنيه مصري منذ عام 2015.',
      stat1Value: 7000,
      stat1Label: 'عميل',
      stat2Value: 1,
      stat2Label: 'مليار جنيه إجمالي تمويلات',
    },
    stats: {
      title: 'التعمير في عشرين عاماً',
      items: [
        { value: 19.905, label: 'مليار جنيه تمويلات منذ الإنشاء', plus: false },
        { value: 12.335, label: 'مليار جنيه محفظة مديونية العملاء الحالية', plus: false },
        { value: 2.1, label: 'مليار جنيه حقوق الملكية', plus: false },
        { value: 40, label: 'ألف عميل', plus: true },
      ],
    },
    csr: {
      title: 'المسؤولية المجتمعية',
      body: 'تعمل الشركة دائماً على تقديم الدعم اللازم لكافة المستويات ودعم كافة شرائح المجتمع المصري بالعمل على ثلاثة اتجاهات أساسية.',
      pillars: [
        {
          title: 'التنمية الإقتصادية',
          desc: 'مساهمتنا في رفع مستوى معيشة الأفراد ونهضة الشركات والمؤسسات من خلال المساهمة في مبادرات البنك المركزي المصري.',
          accent: '#E40521',
          icon: 'BarChart2',
        },
        {
          title: 'التقدم الإجتماعي',
          desc: 'تنمية المجتمع وتنشيطها من خلال تشجيع تحسين الخدمات الصحية والتعليمية ومكافحة البطالة والفقر.',
          accent: '#414042',
          icon: 'Users',
        },
        {
          title: 'حماية البيئة',
          desc: 'المحافظة على البيئة وصيانتها، وتحقيق الإستدامة والتنمية الشاملة والمستدامة.',
          accent: '#6D6E71',
          icon: 'Leaf',
        },
      ],
    },
    partners: {
      title: 'شركاء النجاح',
      subtitle: 'نفخر دائماً بشركائنا من القطاع البنكي والعقاري والذين كانوا سبباً أساسياً في إنجازات الشركة وريادتها عبر السنوات.',
      realEstateTitle: 'شركاء القطاع العقاري',
      items: [
        'مجموعة طلعت مصطفى',
        'إعمار',
        'بالم هيلز',
        'سوديك',
        'نيو جيزة',
        'ماونتن فيو',
      ],
    },
    faq: {
      title: 'الأسئلة الشائعة',
      items: [
        {
          q: 'ما هو التمويل العقاري؟ وكيف يمكننا الإستفادة منه؟',
          a: 'التمويل العقاري هو نشاط مالي غير مصرفي متخصص يقدم حلول ومنتجات مالية طويلة الأجل ومتنوعة للأفراد أو الشركات لإمتلاك وحدة عقارية (سكنية – إدارية – تجارية – خدمية أو طبية) أو لتوفير سيولة بضمان وحدة مملوكة بالفعل، كما يساعد في توفير سيولة مالية للمطورين العقاريين عن طريق حوالات الحق للمحافظ العقارية.',
        },
        {
          q: 'ما هي شركة التعمير للتمويل العقاري (الأولى)؟',
          a: 'التعمير للتمويل العقاري هي أول وأكبر شركة تمويل عقاري بمصر حيث تمتلك التعمير أكبر قاعدة عملاء بمجال التمويل العقاري بالإضافة إلى كونها الشركة الأولى من حيث حجم التمويلات ومحفظة مديونية العملاء منذ الإنشاء.',
        },
        {
          q: 'ما هو سبب تطوير العلامة التجارية للشركة؟',
          a: 'جاء تطوير العلامة التجارية للشركة لمواكبة إستراتيجية الشركة الجديدة والتي تهدف للتطوير الشامل على جميع المستويات وعدم الإكتفاء بالوصول للقمة، بل الحرص على الإستمرار بالقمة والتطور بلا حدود لخدمة عملائنا بشكل أفضل وأيضاً احتفالاً بمرور عشرين عاماً على بدء العمليات بالشركة.',
        },
        {
          q: 'ما هي مزايا التمويل من الشركة عن غيرها؟',
          a: 'عراقة الشركة وجدارتها بثقة عملائها. هيكل مساهمي الشركة من أكبر الجهات والشركات والبنوك الحكومية والخاصة. ملاءة الشركة المالية مما يساعدها على تقديم أكبر مبالغ تمويلية في السوق. تعاون الشركة مع كبار المطورين العقاريين.',
        },
        {
          q: 'ما هو الحد الأقصى للحصول على تمويل من الشركة؟',
          a: '300 مليون جنيه مصري للأفراد، و600 مليون جنيه مصري للشركات.',
        },
        {
          q: 'ما هو الحد الأقصى لقسط التمويل العقاري وكيف يمكن زيادة مبلغ التمويل؟',
          a: 'الحد الأقصى لقسط التمويل العقاري هو 50% من متوسط الدخل الشهري للعميل. يمكن زيادة مبلغ التمويل من خلال: تقديم ما يثبت دخل إضافي، أو تقديم ما يثبت دخل لشريك في ملف التمويل، أو اختيار وحدة ذات قيمة أعلى بما يتناسب مع الدخل.',
        },
        {
          q: 'هل التمويل متاح للمصريين العاملين بالخارج والأجانب؟',
          a: 'نعم، بشرط استيفاء المستندات المطلوبة لكل منهما.',
        },
        {
          q: 'هل يمكن إعادة جدولة أو سداد مبكر للمبلغ المتبقي خلال فترة التمويل؟',
          a: 'نعم، يمكن إعادة جدول الأقساط بناءً على إتفاق العميل مع الشركة، أيضاً يمكن للعميل القيام بسداد كلي أو جزئي في أي وقت من فترة التمويل وتطبق النسب المتفق عليها على الرصيد المتبقي للتمويل.',
        },
      ],
    },
    contact: {
      title: 'تواصل معنا',
      subtitle: 'لتحديث البيانات أو للإستفسارات والشكاوى برجاء ملئ وإرسال الإستمارة التالية',
      form: {
        name: 'الإسم',
        email: 'البريد الإلكتروني',
        phone: 'التليفون',
        reason: 'سبب التواصل',
        reasonOptions: ['تحديث بيانات', 'استفسار', 'شكوى'],
        message: 'الرسالة',
        submit: 'أرسل',
      },
      branches: [
        { name: 'المقر الرئيسي', address: '23، 21 شارع شارل ديجول – برج النيل الإداري – الدور 18 – الجيزة' },
        { name: 'فرع مدينة نصر', address: '14 شارع البطراوي – القاهرة' },
        { name: 'فرع المهندسين', address: '12 شارع سوريا – الجيزة' },
        { name: 'فرع السادس من أكتوبر', address: 'قطعة 94 – امتداد المحور المركزي، بجوار ميدان ليلة القدر' },
        { name: 'فرع العاشر من رمضان', address: 'د11 – مول الدوحة – مشروع الأردنية' },
      ],
      hotline: '19996',
      emails: ['info@aloula-eg.com', 'complaints@aloula-eg.com'],
    },
    guide: {
      title: 'دليل المتعاملين',
      body: 'لمعرفة المزيد عن دليل حماية المتعاملين في القطاع المالي غير المصرفي؛ بإمكانك التحميل من هذا الرابط:',
      cta: 'تحميل الدليل',
    },
    footer: {
      tagline: 'الأولى في التمويل العقاري المصري',
      col1Title: 'روابط سريعة',
      col2Title: 'تواصل معنا',
      address: 'برج النيل الإداري – 23، 21 شارع شارل ديجول – الجيزة – مصر',
      hours: 'الأحد – الخميس، 9:00 صباحاً - 5:00 مساءً',
      emails: ['info@aloula-eg.com', 'complaints@aloula-eg.com'],
      newsletter: {
        label: 'سجل للحصول على آخر الأخبار',
        placeholder: 'البريد الإلكتروني',
        cta: 'سجل',
      },
      bottomBar: 'الشركة خاضعة لإشراف ورقابة الهيئة العامة للرقابة المالية ومقيدة تحت رقم (1) بتاريخ 6/1/2004',
    },
  },

  en: {
    nav: {
      links: [
        { label: 'Home', href: '#home' },
        { label: 'About', href: '#about' },
        { label: 'Products', href: '#products' },
        { label: 'Media Center', href: '#media' },
        { label: 'Client Guide', href: '#guide' },
        { label: 'Contact Us', href: '#contact' },
      ],
      hotline: '19996',
    },
    hero: {
      slides: [
        {
          image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1600',
          headline: 'Al-Tameer Mortgage Finance',
          subline: 'With No Limits',
          cta: 'About Us',
        },
        {
          image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600',
          headline: 'Financing the Future, Building Ambitions',
          subline: '',
          cta: 'Our Products',
        },
        {
          image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1600',
          headline: 'Planning Your Next Step',
          subline: '',
          cta: 'Learn More',
        },
      ],
    },
    about: {
      bannerSubtitle: 'Leading Egypt\'s Mortgage Sector for Over 20 Years',
      headline: 'Al-Tameer Mortgage Finance Company (Al-Oula)',
      body: 'Al-Tameer Mortgage Finance Company (Al-Oula) is the frontrunner company of the mortgage finance sector in Egypt, it\'s the pioneer company of the field since its establishment. The company was founded in August 2003 as a joint venture company by several leading banking and governmental entities. The company started its financial operations in February 2004, and has a current paid-up capital of EGP 1.504 billion.',
      intro: 'Al-Tameer Mortgage Finance is the first national mortgage finance company in Egypt, serving all client segments with specialization and efficiency. We are the main ally for the related sectors to mortgage finance and play an important societal role in contributing to the application of sustainable development standards within the Arab Republic of Egypt.',
      mission: {
        title: 'Our Mission',
        body: 'Our mission is to provide outstanding and advanced financial solutions to our clients by empowering them to achieve their housing and investment goals, prioritizing their satisfaction to enhance the company\'s active role in the development of Egyptian society while ensuring the highest return on investment for our shareholders, and committing to the application of sustainable development standards.',
      },
      vision: {
        title: 'Our Vision',
        body: 'To maintain our leadership in the field and continue its development in light of sustainable development standards.',
      },
      values: {
        title: 'Our Values',
        items: [
          { title: 'Leadership and Development', desc: 'We create innovative solutions and aim beyond our current goals to ensure customer satisfaction and maintain our leadership.' },
          { title: 'Team Spirit', desc: 'We always work as a cohesive, dedicated and collaborative team to enhance the company\'s efficiency and leadership.' },
          { title: 'Superiority', desc: 'Our merit in leadership stems from the precise, harmonious and honest performance of our team members.' },
          { title: 'Commitment and Governance', desc: 'We consistently uphold the principles of best professional practices and work ethics, adhering to fair competition rules and governance at all our business interactions.' },
          { title: 'Sustainability', desc: 'We operate in line with sustainability principles by optimizing the use of resources and promoting green financing development.' },
        ],
      },
      shareholders: {
        title: 'Shareholder Structure',
        items: [
          'New Urban Communities Authority',
          'Housing & Development Bank',
          'Misr Life Insurance Company',
          'Misr Insurance Company',
          'Egyptian Endowments Authority',
          'National Investment Bank',
          'Holding Company for Construction and Development',
          'Misr Iran Development Bank',
          'Arab Contractors for Urban Projects',
          'Alexandria & Saudi Arabia Tourist Projects Company',
          'Nova Park Cairo Company',
          'San Stefano Real Estate Investment Company',
          'Alexandria Real Estate Investment Company',
        ],
      },
      board: {
        title: 'Board of Directors',
        items: [
          { name: 'Tamer Negm', role: 'Chairman of the Board' },
          { name: 'Ayman Abd El-Hameed', role: 'Managing Director & CEO' },
          { name: 'Hassan El-Far', role: 'Board Member' },
          { name: 'Ashraf Negm', role: 'Board Member' },
          { name: 'Ghada El-Bidaiwi', role: 'Board Member' },
          { name: 'Medhat Abd El-Ghany', role: 'Board Member' },
          { name: 'Waleed Abbas', role: 'Board Member' },
          { name: 'Mostafa Abd El-Moniem El-Hayawan', role: 'Board Member' },
          { name: 'Ahmed El-Kamhawy', role: 'Board Member' },
        ],
      },
      management: {
        title: 'Management Team',
        items: [
          {
            name: 'Ayman Abd El-Hameed',
            role: 'Managing Director & CEO',
            bio: 'With over 20 years of experience out of 32 in the fields of mortgage finance and banking. He holds a Bachelor\'s degree in Management Sciences from Sadat Academy. He currently serves as Managing Director & CEO of Al-Tameer Mortgage Finance Company (Al-Oula), after serving as CEO of Amlak – Egypt for Mortgage Finance, and previously led the commercial division at the Commercial International Bank (CIB).',
          },
          {
            name: 'Ahmed Kotb',
            role: 'General Manager – Finance & Treasury Department',
            bio: 'Joined Al-Tameer Mortgage Finance in 2021 with twenty years of experience in internal and external auditing for major local and international companies. He holds a Bachelor\'s degree in Accounting and Finance.',
          },
          {
            name: 'Ahmed Osama',
            role: 'General Manager – Legal Department',
            bio: 'Has been with Al-Tameer since 2021 and has more than nineteen years of experience in the legal field for banking and mortgage finance sectors. He graduated from the Faculty of Law, Ain Shams University, and holds a Master\'s degree in International Trade Law.',
          },
          {
            name: 'Ahmed Nabil',
            role: 'General Manager – Risk Sector',
            bio: 'Joined Al-Tameer in 2021 with nearly twenty years of experience in financial institutions, including banks and mortgage finance companies.',
          },
          {
            name: 'Asmaa Bakr',
            role: 'General Manager – Internal Audit and Supervision Department',
            bio: 'Over 20 years of growing professional experience in providing audit and professional consulting services to multinational companies. She is a Certified Internal Auditor (CIA) from the Institute of Internal Auditors (IIA) - USA.',
          },
          {
            name: 'Mohamed Salama',
            role: 'General Manager – Strategy and External Relations Department',
            bio: 'He has over 17 years of experience in marketing for the real estate and financial institutions sectors. He holds a Bachelor\'s degree in Business Administration and a Master\'s degree in Business Administration with a specialization in Marketing.',
          },
          {
            name: 'Sabry Bakr',
            role: 'Assistant General Manager – IT Department (Software and Applications)',
            bio: 'Holds a Bachelor\'s degree in Commerce with a specialization in Accounting. Sabry has over 20 years of experience in accounting, software and applications. He joined Al-Tameer in 2013.',
          },
          {
            name: 'Neveen Amin',
            role: 'Senior Manager – Branches',
            bio: 'Holds a Bachelor\'s degree in Commerce with a specialization in Business Administration and has 10 years of experience in operations management, logistics and business processes.',
          },
          {
            name: 'Shaimaa Ibrahim',
            role: 'Assistant General Manager – Credit Department',
            bio: 'She has over 17 years of experience in financial institutions. Ms. Shaimaa Ibrahim began her career in the Credit Department at Al-Tameer Mortgage Finance Company.',
          },
          {
            name: 'Mohamed Mostafa',
            role: 'Assistant General Manager – HR Department',
            bio: 'He holds a Bachelor\'s degree in Commerce and a Certified Professional (HRM CP) certificate from the American Chamber of Commerce in Cairo. He has over 20 years of experience.',
          },
          {
            name: 'Mostafa Abd El-Hady',
            role: 'General Manager – Operations Sector',
            bio: 'Joined Al-Tameer in 2023, with over eighteen years of experience in banking and mortgage finance. He holds a CMA certificate from the Institute of Management Accountants in the USA.',
          },
          {
            name: 'Mohamed Hussein',
            role: 'Deputy General Manager – Administration and Purchasing Department',
            bio: 'He holds a Bachelor\'s degree in Commerce and has over 25 years of experience in the real estate sector, spending most of his career in the UAE.',
          },
          {
            name: 'Mohamed Wagdy',
            role: 'Assistant General Manager – Sales and Business Development Department',
            bio: 'He holds a Bachelor degree in Law and has over 9 years of experience in sales and financing sectors.',
          },
        ],
      },
    },
    products: {
      title: 'Our Products and Services',
      bannerSubtitle: 'Committed to Providing the Best Mortgage Solutions',
      cards: [
        {
          title: 'TAMALLOK',
          desc: 'Al-Tameer offers you or your company an exceptional opportunity to finance the purchase of any residential, administrative, commercial, service, or medical unit with a value—among the largest in the industry—with repayment terms extending to many years.',
          accent: '#E40521',
          icon: 'Building2',
          documentsClient: [
            'A copy of the national ID card (for individuals)',
            'Salary certificate (for individuals)',
            'Personal bank statement for a minimum of 6 months for individuals, or a bank statement for a minimum of 1 year for companies',
            'Tax card (for companies)',
            'Commercial register (for companies)',
            'A copy of the company\'s incorporation contract (for companies)',
            'The latest 3 financial statements of the business (for companies)',
          ],
          documentsUnit: [
            'A registered contract for the financed unit (for registered properties)',
            'Handover report (for units located in new cities)',
            'A real estate disposition certificate',
            'Building permit (except for registered units)',
            'Financial and real estate status of the unit (except for registered units)',
            'Notification, allocation decision, or land sale contract for the project site (except for registered units)',
            'Ministerial decree approving the planning and subdivision of the project land',
          ],
        },
        {
          title: 'WAFRA',
          desc: 'Al-Tameer offers you or your company a unique opportunity to obtain financial liquidity—among the largest in the industry—on any residential, administrative, commercial, service, or medical unit with repayment terms extending to many years.',
          accent: '#414042',
          icon: 'TrendingUp',
          documentsClient: [
            'A copy of the national ID card (for individuals)',
            'Salary certificate (for individuals)',
            'Personal bank statement for a minimum of 6 months for individuals, or a bank statement for a minimum of 1 year for companies',
            'Tax card (for companies)',
            'Commercial register (for companies)',
            'A copy of the company\'s incorporation contract (for companies)',
            'The latest 3 financial statements of the business (for companies)',
          ],
          documentsUnit: [
            'A registered contract for the financed unit (for registered properties)',
            'Handover report (for units located in new cities)',
            'A real estate disposition certificate',
            'Building permit (except for registered units)',
            'Financial and real estate status of the unit (except for registered units)',
            'Notification, allocation decision, or land sale contract for the project site (except for registered units)',
            'Ministerial decree approving the planning and subdivision of the project land',
          ],
        },
        {
          title: 'MAHAFEZ',
          desc: 'MAHAFEZ product from Al-Tameer allows real estate development companies to transfer the financial and real estate rights of their real estate portfolio in exchange for financial liquidity—the largest in the financing sector—enabling them to seize new investment opportunities and achieve accelerated growth.',
          accent: '#6D6E71',
          icon: 'Briefcase',
          documentsClient: [
            'Original, recent extract from a valid commercial registry (issued within the last three months)',
            'Copy of the tax card + proof of the latest tax return submission or a certificate from the legal accountant on the tax and insurance status',
            'Copy of the company\'s founding contract / company newspaper (for joint-stock companies), including all amendments',
            'Copy of the lease or ownership contract for the main and subsidiary activity premises',
            'Company bank statement approved by the handling bank for at least the last year',
            'Copies of the last three financial statements approved by the financial auditor and signed by the authorized signatory',
            'Copy of the legal accountant\'s valid membership card',
            'Brief about the company and the board of directors',
          ],
          documentsUnit: [],
        },
      ],
      services: {
        title: 'Our Services',
        items: [
          { title: 'Real Estate Valuation', desc: 'The real estate valuation service during the financing file study enables you to know the fair value of purchasing real estate units to ensure the best investment.', icon: 'Search' },
          { title: 'I-score Report', desc: 'Al-Oula studies the I-score report for clients applying for mortgage financing to make sure that the client is aware of his credit status.', icon: 'FileText' },
          { title: 'Life Insurance', desc: 'Mortgage financing solutions from "Al-Oula" ensure the full settlement of the outstanding debt balance in case of the customer\'s death.', icon: 'Shield' },
          { title: 'Fire Insurance', desc: 'Mortgage financing solutions from "Al-Oula" provide fire insurance coverage for the financed property.', icon: 'Flame' },
        ],
      },
      form: {
        title: 'Inquiry',
        fields: {
          name: 'Name',
          phone: 'Phone Number',
          occupation: 'Occupation',
          occupationOptions: ['Employee', 'Business Owner', 'Freelance', 'Other'],
          unitType: 'Unit Type',
          unitTypeOptions: ['Residential', 'Commercial', 'Administrative', 'Service or Medical', 'Other'],
          product: 'Product',
          productOptions: ['TAMALLOK', 'WAFRA', 'MAHAFEZ'],
          income: 'Monthly Income',
          finance: 'Required Finance',
          inquiry: 'Inquiry',
          submit: 'Submit',
        },
      },
      cta: 'Learn More',
    },
    cbe: {
      headline: 'Central Bank of Egypt Initiative',
      subline: 'Al-Tameer Mortgage Finance Company has played a pioneering role in contributing to and participating in the Central Bank of Egypt\'s initiatives to support mortgage finance for low- and middle-income citizens since its inception, financing over 7,000 clients with a total of more than EGP 1 billion since 2015.',
      stat1Value: 7000,
      stat1Label: 'Clients',
      stat2Value: 1,
      stat2Label: 'Billion EGP Total Financing',
    },
    stats: {
      title: 'Al-Tameer in Twenty Years',
      items: [
        { value: 19.905, label: 'Billion EGP Total Finances Since Inception', plus: false },
        { value: 12.335, label: 'Billion EGP Current Outstanding Portfolio', plus: false },
        { value: 2.1, label: 'Billion EGP Owner\'s Equity', plus: false },
        { value: 40, label: 'Thousand Clients', plus: true },
      ],
    },
    csr: {
      title: 'Corporate Social Responsibility',
      body: 'The company always strives to provide the necessary support at all levels and to all segments of Egyptian society by working on three main directions.',
      pillars: [
        {
          title: 'Economic Development',
          desc: 'Contributing to raising individuals\' living standards and the advancement of companies and institutions through participation in the Central Bank of Egypt\'s initiatives.',
          accent: '#E40521',
          icon: 'BarChart2',
        },
        {
          title: 'Social Progress',
          desc: 'Fostering community development through encouraging the improvement of health and educational services, combating unemployment and poverty.',
          accent: '#414042',
          icon: 'Users',
        },
        {
          title: 'Environmental Protection',
          desc: 'Protecting and maintaining the environment, achieving sustainability, and comprehensive and sustainable development.',
          accent: '#6D6E71',
          icon: 'Leaf',
        },
      ],
    },
    partners: {
      title: 'Success Partners',
      subtitle: 'We are always proud of our partnerships with banking and real estate entities, who have been a fundamental reason for the company\'s achievements and leadership over the years.',
      realEstateTitle: 'Real Estate Partners',
      items: [
        'TMG',
        'EAMAR',
        'Palm Hills',
        'Sodic',
        'New Giza',
        'Mountain View',
      ],
    },
    faq: {
      title: 'Frequently Asked Questions',
      items: [
        {
          q: 'What is mortgage and how can we benefit from it?',
          a: 'Mortgage is a specialized non-banking financial activity that offers long-term and varied financial solutions and products for individuals or companies to acquire real estate units (residential, administrative, commercial, service, or medical). It also provides liquidity by securing a loan against an already owned property and helps provide financial liquidity to real estate developers through portfolio transfers.',
        },
        {
          q: 'What is Al-Tameer Mortgage Finance (Al-Oula)?',
          a: 'Al-Tameer Mortgage Finance is the first and largest mortgage financing company in Egypt. It boasts the largest customer base in the mortgage financing sector and has been the leading company in terms of financing originations and customer portfolios since its establishment.',
        },
        {
          q: 'What is the reason for the company\'s rebranding?',
          a: 'The rebranding of the company aims to align with the new strategy of comprehensive development at all levels. The goal is not only to reach the top but to continue to lead and evolve endlessly to better serve our clients and to celebrate twenty years of operations with the company.',
        },
        {
          q: 'What are the advantages of financing from the company compared to others?',
          a: 'The company\'s long-standing reputation and customer trust. Includes major institutions, companies and government and private banks. Allows the company to offer the largest financing amounts in the market. Enhances financing capabilities and available options.',
        },
        {
          q: 'What is the maximum financing amount available from the company?',
          a: 'EGP 300 million for individuals and EGP 600 million for companies.',
        },
        {
          q: 'What is the maximum financing installment and how can the financing amount be increased?',
          a: 'Maximum installment is 50% of the client\'s average monthly income. Increasing the financing amount can be achieved through: providing proof of additional income, providing proof of income from a partner in the financing application, or selecting a unit of higher value proportional to the income.',
        },
        {
          q: 'Is financing available for Egyptians working abroad and foreigners?',
          a: 'Yes, provided that the required documents for each are submitted.',
        },
        {
          q: 'Can the financing be rescheduled or repaid early during the financing period?',
          a: 'Yes, financing installments can be rescheduled based on an agreement with the company. The client can also make full or partial early repayments at any time during the financing period, with agreed-upon rates applied to the remaining balance.',
        },
      ],
    },
    contact: {
      title: 'Contact Us',
      subtitle: 'For consumer information update / inquiries / complaints please fill in the following form',
      form: {
        name: 'Name',
        email: 'Email',
        phone: 'Phone',
        reason: 'Reason for Contact',
        reasonOptions: ['Information Update', 'Inquiry', 'Complaint'],
        message: 'Message',
        submit: 'Submit',
      },
      branches: [
        { name: 'Headquarters', address: '21, 23 Charles De Gaulle St. – Nile Tower Building – 18th floor – Giza' },
        { name: 'Nasr City Branch', address: '14 Al Batrawy St. – Cairo' },
        { name: 'Mohandessin Branch', address: '12 Syria St. – Giza' },
        { name: '6th of October Branch', address: 'Block 94 – Central Axis Extension – Beside Laylat Al Qadr Square' },
        { name: '10th of Ramadan Branch', address: 'D11 – Doha Mall – Ordonia Project' },
      ],
      hotline: '19996',
      emails: ['info@aloula-eg.com', 'complaints@aloula-eg.com'],
    },
    guide: {
      title: 'Client Guide',
      body: 'To learn more about the Non-Banking Financial Sector Customer Protection Guide, you can download it from this link:',
      cta: 'Download Guide',
    },
    footer: {
      tagline: 'First in Egyptian Mortgage Finance',
      col1Title: 'Quick Links',
      col2Title: 'Contact Us',
      address: 'Nile Tower Building – 21, 23 Charles De Gaulle St. – Giza – Egypt',
      hours: 'Sunday – Thursday, 9:00am – 5:00pm',
      emails: ['info@aloula-eg.com', 'complaints@aloula-eg.com'],
      newsletter: {
        label: 'Sign up to get latest news & listings',
        placeholder: 'Email Address',
        cta: 'Subscribe',
      },
      bottomBar: 'The company is subject to the supervision and control of the Egyptian Financial Regulatory Authority (FRA) and registered under number (1) dated 6/1/2004.',
    },
  },
};